FROM debian:12-slim

ARG APP_VER
ARG URL

ENV LANG="zh_CN.UTF-8"
ENV TZ="Asia/Shanghai"
ENV DISPLAY_WIDTH="1920"
ENV DISPLAY_HEIGHT="1080"
ENV HOME=/config
ENV LC_ALL=C

RUN apt-get update --ignore-missing

RUN apt-get install -y --no-install-recommends --fix-missing \
        ca-certificates \
        curl \
        bzip2 \
        lsb-release

RUN OS_ARCH=$(dpkg --print-architecture) && \
    DEB_FILE=/baidunetdisk_${APP_VER}_${OS_ARCH}.deb && \
    DEB_URL=https://pkg-ant.baidu.com/issue/netdisk/LinuxGuanjia/${APP_VER}/baidunetdisk_${APP_VER}_${OS_ARCH}.deb && \
    echo ${DEB_URL}
    curl -fsSL ${DEB_URL} -o ${DEB_FILE} && \
    dpkg -i ${DEB_FILE} && \
    rm ${DEB_FILE}
    
# clean baidunetdisk
RUN cd /opt/baidunetdisk \
    && tar -cjvf LICENSES.chromium.html.tar.bz2 LICENSES.chromium.html \
    && rm LICENSES.chromium.html \
    && cd / \
    && rm -rf /opt/baidunetdisk/resources/app.asar.unpacked/node_modules/@baidu/clipboard-listen-macos/src \
    # clear font cache
    && rm -rf /var/cache/fontconfig/* \

# clear apt cache
RUN apt-get purge --autoremove -y curl bzip2 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/log/*.log

# Clean temp apt source & reset debian apt source
RUN echo "#!/bin/sh\n/opt/baidunetdisk/baidunetdisk --disable-gpu-sandbox --no-sandbox" > /startapp.sh \
    # set /startapp.sh
    && chmod +x /startapp.sh \
    # openbox
    && mkdir -p /etc/openbox \
    && echo "<Type>normal</Type>\n<Name>Baidunetdisk</Name>" > /etc/openbox/main-window-selection.xml \
    # set /config/.config/mimeapps.list
    && mkdir -p /config/.config \
    && echo "\n[Default Applications]\nx-scheme-handler/baiduyunguanjia=baidunetdisk.desktop" > /config/.config/mimeapps.list \
    && chmod 777 /config/.config/mimeapps.list

ENTRYPOINT ["/init"]