# Pull base image.
FROM debian:12-slim

# Install system packages.
RUN apt-get update && apt-get install -y --no-install-recommends \
    # Used to determine if nginx is ready.
    netcat-openbsd \
    # For ifconfig
    net-tools \
    # Needed to generate self-signed certificates
    openssl \
    # Needed for VNC
    tigervnc-standalone-server tigervnc-common \
    # Needed for Openbox
    openbox \
    # Needed for Nginx
    nginx \
    # Needed for noVNC
    novnc \
    # Clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set environment variables.
ENV DISPLAY_WIDTH=1920 \
    DISPLAY_HEIGHT=1080 \
    DARK_MODE=0 \
    SECURE_CONNECTION=0 \
    SECURE_CONNECTION_VNC_METHOD=SSL \
    SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60 \
    WEB_LISTENING_PORT=5800 \
    VNC_LISTENING_PORT=5900 \
    VNC_PASSWORD="" \
    ENABLE_CJK_FONT=0

# Expose ports.
#   - 5800: VNC web interface
#   - 5900: VNC
EXPOSE 5800 5900
